### ISSUE TITLE
CodeMirror not defined

### ISSUE THREAD

**Issue by ciel** [sparksuite/simplemde-markdown-editor#355]
I just upgraded from version `1.10.1` to `1.11.0`, and the exact same setup I had before now throws the error...

> CodeMirror is not defined

anywhere that SimpleMDE tries to use CodeMirror. Reverting back to `1.10.1` resolves the problem. I'm really not sure where the error could be; my gulpfile just copies `node_modules/simplemde/dist/simplemde.min.js` to the requisite scripts directory in my application. It's worked great up until `1.11.0`.

**Comment by WesCossick** [comment]
I can't reproduce this. Can you replicate it using JSFiddle?

**Comment by ciel** [comment]
I'll try. Though I might be more specific; It fails with `SystemJS` module loader, while `1.10.1` worked fine with it.

**Comment by ciel** [comment]
If I copy over the files directly from github, it works - but using the ones from `npm` does not work. I do not know how, but it appears they aren't the same.

**Comment by WesCossick** [comment]
Interestingly enough, there appears to be sizable differences between what NPM has and what GitHub has. GitHub's code is correct. I'll see what I can do.

**Comment by WesCossick** [comment]
Should be fixed now in `1.11.1`. Let me know if not.

**Comment by kasparasg** [comment]
The issue seems to be present still :(

**Comment by kasparasg** [comment]
@WesCossick not sure if https://github.com/NextStepWebs/codemirror-spell-checker was published to NPM correctly. The source doesn't seem to reflect what's on git?

**Comment by robbieaverill** [comment]
@WesCossick - fiddle here to demonstrate a simple installation failing with the "CodeMirror is not defined" console error: https://jsfiddle.net/o80upuzL/

**Comment by kasparasg** [comment]
A temporary workaround in my `package.json` I've referenced this:

`"codemirror-spell-checker": "git@github.com:NextStepWebs/codemirror-spell-checker.git#e2c7e3b67438cf1202f1081d55d2a3f71f2779ff"`

**Comment by robbieaverill** [comment]
@WesCossick - your website is an example as well: https://simplemde.com/

**Comment by WesCossick** [comment]
Neither the JSFiddle nor the demo website exhibit the issue you've suggested. Potentially it's a browser or OS specific issue. What browser and OS are y'all using?

**Comment by robbieaverill** [comment]
@WesCossick you're right. It's failing in Firefox Developer Edition, but working in Chrome (OSX)

**Comment by kasparasg** [comment]
For me it was failing on Chrome (OSX). But it felt like the package installed locally had a pretty old version of the code on the spell checker, hence me referencing a commit SHA instead.

**Comment by robbieaverill** [comment]
It's failing on Chrome (OSX) now for me too.

**Comment by WesCossick** [comment]
Can identify where in the code this error first appears? I still cannot replicate it.

**Comment by robbieaverill** [comment]
```
Uncaught ReferenceError: CodeMirror is not defined (simplemde.min.js:7)
Uncaught ReferenceError: SimpleMDE is not defined (my page)
```

CM trace:

```
r.4.typo-js               @ simplemde.min.js:7
i                         @ simplemde.min.js:7
(anonymous function)      @ simplemde.min.js:7
r.20../codemirror/tablist @ simplemde.min.js:14
i                         @ simplemde.min.js:7
t                         @ simplemde.min.js:7
(anonymous function)      @ simplemde.min.js:7
(anonymous function)      @ simplemde.min.js:7
(anonymous function)      @ simplemde.min.js:7
```

**Comment by WesCossick** [comment]
Could you provide that same info, but using the [debug version](https://github.com/NextStepWebs/simplemde-markdown-editor/blob/master/debug/simplemde.debug.js)? Here's a CDN version: https://cdn.rawgit.com/NextStepWebs/simplemde-markdown-editor/master/debug/simplemde.debug.js

**Comment by robbieaverill** [comment]
Sure:

```
spell-checker.js:25 Uncaught ReferenceError: CodeMirror is not defined
    4.typo-js             @ spell-checker.js:25
    s                     @ b64.js:6
    (anonymous function)  @ b64.js:620
    ../codemirror/tablist @ simplemde.js:19
    s                     @ b64.js:6
    e                     @ b64.js:6
    (anonymous function)  @ b64.js:6
    (anonymous function)  @ b64.js:6
    (anonymous function)  @ b64.js:6
```

**Comment by robbieaverill** [comment]
If I include CodeMirror before SimpleMDE, it works again provided I disable spell checking when instantiating the editor. If I don't disable it I get `TypeError: CodeMirrorSpellChecker is not a function`. Broken dependency loading?

**Comment by justusburger** [comment]
Got the same issue. It's also showing on https://simplemde.com/.

Note that I did NOT upgrade. So I'm guessing the plugin is loading some assets that have changed or something. 

<img width="1850" alt="screen shot 2016-06-10 at 3 28 16 pm" src="https://cloud.githubusercontent.com/assets/4091173/15966537/e2d699c2-2f23-11e6-9453-f2fbb76f1ffc.png">

**Comment by WesCossick** [comment]
No matter what browser and OS combination I use, I cannot replicate this issue. If someone who is able to can identify the problem, fix it, and submit a PR, that would be tremendously helpful.

**Comment by WesCossick** [comment]
@justusburger, what browser and OS versions are you using?

**Comment by WesCossick** [comment]
For reference, I'm primarily using Chrome 51.0.2704.84 m (64-bit) on Windows 10.

**Comment by justusburger** [comment]
@WesCossick I'm also on 51.0.2704.84 (64-bit), but on OSX.

**Comment by justusburger** [comment]
I'll have a look when I have a moment.

**Comment by vinerz** [comment]
+1 here. Using the master branch directly.

**Comment by danabrey** [comment]
Just for info, I get no such issue on simplemde.com using Windows 7, Chrome 64-bit 51.0.2704.84 m, nor on the same Chrome version in a Mac OSX VM. @justusburger Are you still seeing this error there?

**Comment by royguo** [comment]
Same issue here:

```
spell-checker.js:25Uncaught ReferenceError: CodeMirror is not defined4.typo-js 
@ spell-checker.js:25s 
@ b64.js:6(anonymous function) 
@ b64.js:620../codemirror/tablist 
@ simplemde.js:19s 
@ b64.js:6e 
@ b64.js:6(anonymous function) 
@ b64.js:6(anonymous function) 
@ b64.js:6(anonymous function) 
@ b64.js:6
2:191 Uncaught ReferenceError: SimpleMDE is not defined
```

OS X, Chrome latest version

**Comment by buszu** [comment]
I've just got the same issue with:
- Chrome 51.0.2704.84,
- Chromium 45.0.2454.101,
- Firefox 41.0.1
  running on LinuxMint 17 (64-bit).

The issue occurred only for version `1.11.1` of simplemde. Downgrading to `1.11.0` solved the problem.

**Comment by justusburger** [comment]
@WesCossick If I let you teamviewer into my Mac to debug yourself, would that help?

**Comment by mseymour** [comment]
Getting it here as well. It seems to happen on and off. 1.11.1.

**Comment by hootlex** [comment]
I face the same issue. It was working perfectly and suddenly I got this error.
I am using the cdn version.
**v1.11.0 works fine.**

**Comment by alfhen** [comment]
The following fiddle reproduces the bug using the [raw debug](https://raw.githubusercontent.com/NextStepWebs/simplemde-markdown-editor/00e0f69d9378979f58e0ebf07dc2da9b9d70f083/debug/simplemde.js) of v1.1.11:  

https://jsfiddle.net/alfhen/vofs9Lqz/10/

The bug occurs in both Safari and Chrome.

**Comment by WesCossick** [comment]
I think I found the issue. It looks like CodeMirror Spell Checker is using an older version of the code. Possibly the project was not built correctly or was not published to NPM correctly. I'm fixing this now...

**Comment by WesCossick** [comment]
Should be fixed now!

**Comment by molayodecker** [comment]
Issue still persist SimpleMDE is not defined. 
jsDelivr works fine though

**Comment by SinMu-L** [comment]
> 问题仍然存在 SimpleMDE 未定义。 jsDelivr 工作正常

I tried the versions of 1.11.2, 1.11.1, 1.11.0. But my code still prompts `Uncaught ReferenceError: SimpleMDE is not defined`, I checked all the solutions to the issue, but it still hasn't been resolved
